let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Tomato",
    price: 45,
    desc: "100% Organic.",
    img: "fruit&vege/5.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Carrots",
    price: 100,
    desc: "100% Organic",
    img: "fruit&vege/6.jpg",
  },
  {
    id: "wuefbcxbsn",
    name: "Onion",
    price: 25,
    desc: "100% Organic.",
    img: "fruit&vege/7.jpg",
  },
  {
    id: "thyfhccv",
    name: "Pumkin",
    price: 300,
    desc: "100% Organic.",
    img: "fruit&vege/15.jpg",
  },
  {
    id: "jfhgbvncs",
    name: "Potato",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/14.jpg",
  },
  {
    id: "ioytrhndv",
    name: "EggPlant",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/17.jpg",
  },
  {
    id: "jfhgvnscs",
    name: "LadyFinger",
    price: 45,
    desc: "100% Organic.",
    img: "fruit&vege/18.jpg",
  },
  {
    id: "iotrhndcv",
    name: "Ginger",
    price: 100,
    desc: "100% Organic",
    img: "fruit&vege/19.jpg",
  },
  {
    id: "wuefbxbsn",
    name: "Garlic",
    price: 25,
    desc: "100% Organic.",
    img: "fruit&vege/20.jpg",
  },
  {
    id: "thfhcxcv",
    name: "Broccoli",
    price: 300,
    desc: "100% Organic.",
    img: "fruit&vege/21.jpg",
  },
  {
    id: "jfhgvncs",
    name: "Mint",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/22.jpg",
  },
  {
    id: "ioytrndv",
    name: "Cherry Tomato",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/4.jpg",
  },
  {
    id: "thzfhccv",
    name: "Broccoli",
    price: 300,
    desc: "100% Organic.",
    img: "fruit&vege/21.jpg",
  },
  {
    id: "jfhgvncxs",
    name: "Corinader",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/22.jpg",
  },
  {
    id: "ioytrxdv",
    name: "Green chilli",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/download.jpeg",
  },
  /*fruits*/
  {
    id: "jfhxgvcs",
    name: "peach",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/3.jpg",
  },
  {
    id: "ioytnxdv",
    name: "Water Melon",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/9.jpg",
  },
  {
    id: "jfgvxcs",
    name: "Mango",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/10.jpg",
  },
  {
    id: "iotnxdv",
    name: "Apple",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/11.jpg",
  },
  {
    id: "kivi",
    name: "Kivi",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/12.jpg",
  },
  {
    id: "Pomigrant",
    name: "Pomigrant",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/16.jpg",
  },
  {
    id: "Banana",
    name: "Banana",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/28.jpg",
  },
  {
    id: "Orange",
    name: "Orange",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/31.jpg",
  },
  {
    id: "berry",
    name: "Berry",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/24.jpg",
  },
  {
    id: "Cherry",
    name: "Cherry",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/25.jpg",
  },
  {
    id: "staberry",
    name: "Staberry",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/26.jpg",
  },
  {
    id: "Melon",
    name: "Melon",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/30.jpg",
  },
  {
    id: "Papaya",
    name: "Papaya",
    price: 45,
    desc: "100% Organic.",
    img: "fruit&vege/29.jpg",
  },
  {
    id: "DragonFruit",
    name: "Dragon Fruit",
    price: 100,
    desc: "100% Organic.",
    img: "fruit&vege/27.jpg",
  },
  {
    id: "Litchi",
    name: "Litchi",
    price: 45,
    desc: "100% Organic .",
    img: "fruit&vege/32.jpg",
  },
  /*meat and poultry*/
  {
    id: "beef",
    name: "beef",
    price: 100,
    desc: "100% Organic.",
    img: "dairy&Egg/27.jpeg",
  },
  {
    id: "mutton",
    name: "Mutton",
    price: 45,
    desc: "100% Organic.",
    img: "dairy&Egg/26.jpeg",
  },
  {
    id: "MilkPak",
    name: "Milk Pak",
    price: 100,
    desc: "100% Organic",
    img: "dairy&Egg/11.jpeg",
  },
  {
    id: "Yogurt",
    name: "Yogurt",
    price: 25,
    desc: "100% Organic.",
    img: "dairy&Egg/17.webp",
  },
  {
    id: "Cheese",
    name: "Cheese",
    price: 300,
    desc: "100% Organic.",
    img: "dairy&Egg/25.jpg",
  },
  {
    id: "Egg",
    name: "Egg",
    price: 45,
    desc: "100% Organic .",
    img: "dairy&Egg/22.jpg",
  },
  {
    id: "Chicken",
    name: "Chicken",
    price: 100,
    desc: "100% Organic.",
    img: "dairy&Egg/28.jpg",
  },
  {
    id: "DUCKegg",
    name: "Duck Egg",
    price: 45,
    desc: "100% Organic.",
    img: "dairy&Egg/15.jpeg",
  },
  {
    id: "butter",
    name: "Butter",
    price: 100,
    desc: "100% Organic",
    img: "dairy&Egg/24.jpg",
  },
  {
    id: "cream",
    name: "Cream",
    price: 25,
    desc: "100% Organic.",
    img: "dairy&Egg/12.jpeg",
  },
  {
    id: "Ostrish",
    name: "Ostrish Egg",
    price: 300,
    desc: "100% Organic.",
    img: "dairy&Egg/23.jpg",
  },
  {
    id: "ccream",
    name: "Cream Cheese",
    price: 45,
    desc: "100% Organic .",
    img: "dairy&Egg/18.jpeg",
  },
  {
    id: "Blue",
    name: "Blue Berry Greek Yogurt",
    price: 100,
    desc: "100% Organic.",
    img: "dairy&Egg/19.jpg",
  },
  {
    id: "Condess",
    name: "Condence Milk",
    price: 300,
    desc: "100% Organic.",
    img: "dairy&Egg/13.jpeg",
  },
  {
    id: "Unsalt",
    name: "Unsalted Butter",
    price: 45,
    desc: "100% Organic .",
    img: "dairy&Egg/5.jpg",
  },
  /*snacks*/
  {
    id: "noodles",
    name: "Noodles",
    price: 100,
    desc:"best price",
    img: "snacks/1.jpg",
  },
  {
    id: "upp",
    name: "7up",
    price: 100,
    desc:"best price",
    img: "snacks/2.jpg",
  },
  {
    id: "Tea",
    name: "Tea",
    price: 100,
    desc:"best price",
    img: "snacks/3.jpg",
  },
  {
    id: "GranolaBars",
    name: "Granola Bars",
    price: 1000,
    desc:"best price",
    img: "snacks/4.jpg",
  },
  {
    id: "noo",
    name: "Monster Energy Drink",
    price: 1800,
    desc:"best price",
    img: "snacks/5.jpeg",
  },
  {
    id: "sniker",
    name: "Snikers",
    price: 100,
    desc:"best price",
    img: "snacks/6.png",
  },
  {
    id: "noes",
    name: "Dairy Milk",
    price: 1080,
    desc:"best price",
    img: "snacks/7.jpeg",
  },
  {
    id: "Dark",
    name: "Dark Chocolate",
    price: 9100,
    desc:"best price",
    img: "snacks/8.jpeg",
  },
  {
    id: "n",
    name: "Cocacola",
    price: 10,
    desc:"best price",
    img: "snacks/9.jpeg",
  },
  {
    id: "co",
    name: "Coffee",
    price: 100,
    desc:"best price",
    img: "snacks/10.jpg",
  },
  {
    id: "noodexs",
    name: "Maggi",
    price: 100,
    desc:"best price",
    img: "snacks/1.jpg",
  },
  {
    id: "lay",
    name: "lays",
    price: 100,
    desc:"best price",
    img: "snacks/11.jpg",
  },
  {
    id: "la",
    name: "Candies",
    price: 100,
    desc:"best price",
    img: "snacks/12.jpeg",
  },
  {
    id: "laxy",
    name: "Chocolate pack",
    price: 1000,
    desc:"best price",
    img: "snacks/13.jpeg",
  },
  {
    id: "dew",
    name: "dew",
    price: 100,
    desc:"best price",
    img: "snacks/14.jpeg",
  },
/* spices */
{
  id: "de",
  name: "Chana dal",
  price: 100,
  desc:"best price",
  img: "spices/1.jpg",
},
{
  id: "atta",
  name: "Atta",
  price: 100,
  desc:"best price",
  img: "spices/2.jpg",
},
{
  id: "niharii",
  name: "Nihari masala",
  price: 10,
  desc:"best price",
  img: "spices/3.jpeg",
},
{
  id: "black",
  name: "Black papper",
  price: 100,
  desc:"best price",
  img: "spices/4.jpeg",
},
{
  id: "mung",
  name: "Mung dal",
  price: 100,
  desc:"best price",
  img: "spices/5.jpeg",
},
{
  id: "rice",
  name: "Rice",
  price: 100,
  desc:"best price",
  img: "spices/6.jpeg",
},
{
  id: "white",
  name: "White atta",
  price: 100,
  desc:"best price",
  img: "spices/7.jpeg",
},
{
  id: "cinnimon",
  name: "Cinnimon",
  price: 100,
  desc:"best price",
  img: "spices/8.jpeg",
},
{
  id: "Baryani",
  name: "Baryani masala",
  price: 100,
  desc:"best price",
  img: "spices/9.jpeg",
},
{
  id: "paya",
  name: "paya masala",
  price: 100,
  desc:"best price",
  img: "spices/10.jpeg",
},
{
  id: "chilli",
  name: "Chilli powder",
  price: 100,
  desc:"best price",
  img: "spices/11.jpeg",
},
{
  id: "red",
  name: "Red beans",
  price: 100,
  desc:"best price",
  img: "spices/13.jpeg",
},
{
  id: "salt",
  name: "salt",
  price: 100,
  desc:"best price",
  img: "spices/14.jpeg",
},
];